export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_ORDERS_FETCH_SUCCESS = 'PRODUCT_ORDERS_FETCH_SUCCESS';
export const PRODUCT_SUPPLIES_FETCH_SUCCESS = 'PRODUCT_SUPPLIES_FETCH_SUCCESS';
export const CUSTOMER_ITEMS_FETCH_SUCCESS = 'CUSTOMER_ITEMS_FETCH_SUCCESS';
export const PRODUCT_CHANGE_STATUS = 'PRODUCT_CHANGE_STATUS';
