export const CUSTOMER_FETCH_SUCCESS = 'CUSTOMER_FETCH_SUCCESS';
export const CUSTOMER_ORDERS_FETCH_SUCCESS = 'CUSTOMER_ORDERS_FETCH_SUCCESS';
export const CUSTOMER_ITEMS_FETCH_SUCCESS = 'CUSTOMER_ITEMS_FETCH_SUCCESS';
